server=http://127.0.0.1:5000/
apiVersion=api/v1/
# with_validation_fix ??? ??????????

backend.profile=WITH_VALIDATION_FIX

admin.username=admin
admin.password=admin

ui.remote=
ui.baseUrl=http://localhost:3000
browser=firefox
browser.size=1400x900
browser.holdOpen=true

db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers
