# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response

NewUserRequest=NewUserResponse:username=username,role=role
NewUserResponse=GetCustomerProfileResponse:id=id,username=username,role=role,password=password
Customer=NewUserResponse:id=id,username=username,role=role,password=password
MakeDepositRequest=MakeDepositResponse:id=id,balance=balance
MakeDepositResponse=Transaction:balance=amount,id=relatedAccountId
TransferMoneyRequest=TransferMoneyResponse:senderAccountId=senderAccountId,\
  receiverAccountId=receiverAccountId,amount=amount
