replicaCount: 1
imagePullPolicy: IfNotPresent

backend:
  image: nobugsme/nbank:with_validation_fix
  port: 4111
  nodePort: 30447
frontend:
  enabled: false
  image: nobugsme/nbank-ui:with_nginx
  port: 80
  nodePort: 32538