### Часть 2: Перевод денег с одного аккаунта на другой

### Тест-кейсы в этом файле:

### Тест-кейс 1: Авторизованный юзер переводит 0 при балансе выше 0
### Тест-кейс 2: Авторизованный Юзер переводит -1 при балансе выше 0
### Тест-кейс 3: Авторизованный юзер переводит 10 001 другому юзеру
### Тест-кейс 4: Авторизованный юзер переводит сумму 10 000 при 0 на балансе
### Тест-кейс 5: Авторизованный юзер отправляет сумму больше чем на балансе на аккаунте с которого отправляет
### Тест-кейс 6: Авторизованный юзер имеет 2 счета и делает перевод с одного своего счета на другой свой счет
### Тест-кейс 7: Авторизованный юзер делает перевод на несуществующий аккаунт

######################################### Тест-кейс 1: Авторизованный юзер переводит 0 при балансе выше 0
### Предусловия: Админ создает 2 юзера. Оба создают себе по 1 аккаунту каждый. Предполагаемый юзер-дебет делает депозит.
### Действие: Юзер-дебет делает перевод на аккаунт юзера 2 на сумму 0
### Ожидаемый результат: ошибка

### Админ создает юзера 1
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate",
  "password": "15101996Kate!",
  "role": "USER"
}


### Админ создает юзера 2
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "polina",
  "password": "15101996Polina!",
  "role": "USER"
}

### Юзер 1 авторизовывается. Вытаскиваем токен.
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "kate",
  "password": "15101996Kate!"
}

### Юзер 1 создает счет.
POST http://localhost:5000/api/v1/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверяем, что счет создался
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Действие: Юзер 1 делает депозит на свой счет
POST http://localhost:5000/api/v1/accounts/deposit
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh
Content-Type: application/json

{
  "id": 1,
  "balance": 100
}

### Проверяем, что депозит 100 появился на счете "1"
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Юзер 2 авторизуется. Вытаскиваем токен
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "polina",
  "password": "15101996Polina!"
}

### Юзер 2 создает счет
POST http://localhost:5000/api/v1/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==

### Проверяем, что счет создался и записываем его ID чтобы потом подставить
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==


### Действие: юзер 1 делает перевод на сумму 0 на счет юзера 2.
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

{
  "senderAccountId": 3,
  "receiverAccountId": 2,
  "amount": 0
}

### Ожидаемый результат: 400 bad request Invalid transfer: insufficient funds or invalid accounts

### Проверка: у юзера 1 баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверка 2: у юзера 2 баланс такой же баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==

### Удаляем данные: Админ получает id всех юзеров
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/2
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/3
Authorization: Basic YWRtaW46YWRtaW4=

### Проверяем, что пользователей нет
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=


######################### Тест-кейс 2: Авторизованный Юзер переводит -1 при балансе выше нуля
### Предусловия: Админ создает 2 юзера. Оба создают себе по 1 аккаунту каждый. Предполагаемый юзер-дебет делает депозит
### Действие: Юзер-дебет отправляет с существующего счета -1 на существующий счет юзера-кредита
### Ожидаемый результат: ошибка

###Админ создает юзера 1
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate",
  "password": "15101996Kate!",
  "role": "USER"
}


###Админ создает юзера 2
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "polina",
  "password": "15101996Polina!",
  "role": "USER"
}

### Юзер 1 авторизовывается. Вытаскиваем токен.
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "kate",
  "password": "15101996Kate!"
}


### Юзер 1 создает счет.
POST http://localhost:5000/api/v1/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Проверяем, что счет создался
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Действие: Юзер 1 делает депозит на свой счет
POST http://localhost:5000/api/v1/accounts/deposit
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh
Content-Type: application/json

{
  "id": 1,
  "balance": 100
}

### Проверяем, что депозит 100 появился на счете "1"
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Юзер 2 авторизуется. Вытаскиваем токен
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "polina",
  "password": "15101996Polina!"
}

### Юзер 2 создает счет
POST http://localhost:5000/api/v1/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==


### Проверяем, что счет создался и записываем его ID чтобы потом подставить
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==


### Действие: юзер 1 делает перевод на сумму 0 на счет юзера 2.
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

{
  "senderAccountId": 3,
  "receiverAccountId": 2,
  "amount": 0
}

### Ожидаемый результат: 400 bad request Invalid transfer: insufficient funds or invalid accounts

### Проверка: у юзера 1 баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверка 2: у юзера 2 баланс такой же баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==

### Удаляем данные: Админ получает id всех юзеров
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/2
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/3
Authorization: Basic YWRtaW46YWRtaW4=

### Проверяем, что пользователей нет
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=

######################################## Тест-кейс 3: Авторизованный юзер переводит 10 001 другому юзеру
### Предусловия: Админ создает 2 юзера. Оба создают себе по 1 аккаунту каждый. Предполагаемый юзер-дебет делает депозит 3 раза по 5000.
### Действие: Юзер-дебет отправляет с существующего счета 10001 на существующий счет юзера-кредита
### Ожидаемый результат: ошибка

### Админ создает юзера 1
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate",
  "password": "15101996Kate!",
  "role": "USER"
}


### Админ создает юзера 2
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "polina",
  "password": "15101996Polina!",
  "role": "USER"
}

### Юзер 1 авторизовывается. Вытаскиваем токен.
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "kate",
  "password": "15101996Kate!"
}

### Юзер 1 создает счет.
POST http://localhost:5000/api/v1/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверяем, что счет создался
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Действие: Юзер 1 делает депозит на свой счет 3 раза (чтобы сумма была выше 10 001)
POST http://localhost:5000/api/v1/accounts/deposit
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh
Content-Type: application/json

{
  "id": 1,
  "balance": 5000
}

### Проверяем, что у юзера на счету 15 000
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Юзер 2 авторизуется. Вытаскиваем токен
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "polina",
  "password": "15101996Polina!"
}

### Юзер 2 создает счет
POST http://localhost:5000/api/v1/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==

### Проверяем, что счет создался и записываем его ID чтобы потом подставить
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==

### Действие: юзер 1 делает перевод на сумму 0 на счет юзера 2.
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

{
  "senderAccountId": 3,
  "receiverAccountId": 2,
  "amount": 10001
}

### Ожидаемый результат: 400, Transfer amount cannot exceed 10000

### Проверка: у юзера 1 баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверка 2: у юзера 2 баланс такой же баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==

### Удаляем данные: Админ получает id всех юзеров
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/2
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/3
Authorization: Basic YWRtaW46YWRtaW4=

### Проверяем, что пользователей нет
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=

########################### Тест-кейс 4: Авторизованный юзер переводит сумму 10 000 при 0 на балансе
### Предусловия: Админ создает 2 юзера. Оба создают себе по 1 аккаунту каждый.
### Действие: Юзер-дебет отправляет с существующего счета 2 на существующий счет юзера-кредита
### Ожидаемый результат: ошибка

###Админ создает юзера 1
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate",
  "password": "15101996Kate!",
  "role": "USER"
}


###Админ создает юзера 2
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "polina",
  "password": "15101996Polina!",
  "role": "USER"
}

### Юзер 1 авторизовывается. Вытаскиваем токен.
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "kate",
  "password": "15101996Kate!"
}


### Юзер 1 создает счет.
POST http://localhost:5000/api/v1/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Проверяем, что счет создался
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверяем, что на балансе 0
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Юзер 2 авторизуется. Вытаскиваем токен
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "polina",
  "password": "15101996Polina!"
}

### Юзер 2 создает счет
POST http://localhost:5000/api/v1/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==


### Проверяем, что счет создался и записываем его ID чтобы потом подставить
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==


### Действие: юзер 1 делает перевод на сумму 10000 на счет юзера 2.
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

{
  "senderAccountId": 3,
  "receiverAccountId": 2,
  "amount": 10000
}

### Ожидаемый результат: 400 bad request Invalid transfer: insufficient funds or invalid accounts

### Проверка: у юзера 1 баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверка 2: у юзера 2 баланс такой же баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==

### Удаляем данные: Админ получает id всех юзеров
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/2
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/3
Authorization: Basic YWRtaW46YWRtaW4=

### Проверяем, что пользователей нет
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=


### Тест-кейс 5: Авторизованный юзер отправляет сумму больше чем на балансе на аккаунте с которого отправляет
### Предусловия: Предусловия: Админ создает 2 юзера. Оба создают себе по 1 аккаунту каждый. Предполагаемый юзер-дебет делает депозит на 1
### Действие: Юзер 1 отправляет 2
### ### Ожидаемый результат: ошибка

###Админ создает юзера 1
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate",
  "password": "15101996Kate!",
  "role": "USER"
}


###Админ создает юзера 2
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "polina",
  "password": "15101996Polina!",
  "role": "USER"
}

### Юзер 1 авторизовывается. Вытаскиваем токен.
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "kate",
  "password": "15101996Kate!"
}


### Юзер 1 создает счет.
POST http://localhost:5000/api/v1/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Проверяем, что счет создался
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Действие: Юзер 1 делает депозит 100 на свой счет
POST http://localhost:5000/api/v1/accounts/deposit
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh
Content-Type: application/json

{
  "id": 1,
  "balance": 100
}

### Проверяем, что депозит 100 появился на счете "1"
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Юзер 2 авторизуется. Вытаскиваем токен
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "polina",
  "password": "15101996Polina!"
}

### Юзер 2 создает счет
POST http://localhost:5000/api/v1/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==


### Проверяем, что счет создался и записываем его ID чтобы потом подставить
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==


### Действие: юзер 1 делает перевод на сумму 101 на счет юзера 2.
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

{
  "senderAccountId": 3,
  "receiverAccountId": 2,
  "amount": 101
}

### Ожидаемый результат: 400 bad request Invalid transfer: insufficient funds or invalid accounts

### Проверка: у юзера 1 баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверка 2: у юзера 2 баланс такой же баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==

### Удаляем данные: Админ получает id всех юзеров
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/2
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/3
Authorization: Basic YWRtaW46YWRtaW4=

### Проверяем, что пользователей нет
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=


######################### Тест-кейс 6: Авторизованный юзер имеет 2 счета и делает перевод с одного своего счета на другой свой счет
### Предусловие: Админ создал юзера. Юзер авторизовался. Юзер имеет 2 аккаунта. На оба делает депозит.
### Действие: с аккаунта Н делаем перевод на аккаунт М
### Ожидаемый результат: ошибка


###Админ создает юзера 1
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate",
  "password": "15101996Kate!",
  "role": "USER"
}


### Юзер 1 авторизовывается. Вытаскиваем токен.
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "kate",
  "password": "15101996Kate!"
}


### Юзер 1 создает счет (два раза этот запрос)
POST http://localhost:5000/api/v1/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Проверяем, что счета создались
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Действие: Юзер 1 делает депозит на свой счет 1
POST http://localhost:5000/api/v1/accounts/deposit
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh
Content-Type: application/json

{
  "id": 1,
  "balance": 100
}


### Проверяем, что депозит 100 появился на счете "1"
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Действие: Юзер 1 делает депозит на свой счет 2
POST http://localhost:5000/api/v1/accounts/deposit
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh
Content-Type: application/json

{
  "id": 2,
  "balance": 35
}


### Проверяем, что депозит 35 появился на счете "2"
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Действие: юзер 1 делает перевод на сумму 15 на свой второй счет
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 0
}

### Ожидаемый результат: ошибка ?
### Фактический результат: баг? перевод удался! Но не совсем понятно, в требованиях имеется ввиду "перевод самому себе" - это нельзя указать отправителем и получателем
### один и тот же аккаунт или в рамках юзера?

### Проверка: у юзера 1 на счету 1 баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверка: у юзера 1 на счету 2 баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Удаляем данные: Админ получает id всех юзеров
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/3
Authorization: Basic YWRtaW46YWRtaW4=

### Проверяем, что пользователей нет
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=


### Тест-кейс 7: Авторизованный юзер делает перевод на несуществующий аккаунт
### Предусловие: Админ создает юзера. Админ смотрит getAllUser чтобы собрать, какие еще есть счета.
### Действие: Юзер делает перевод на несуществ счет. В качестве получателя используем ту цифру, которая не фигурирует ни в чьих аккаунтах
### Ожидаемый результат: ошибка


###Админ создает юзера 1
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "kate",
  "password": "15101996Kate!",
  "role": "USER"
}


###Админ создает юзера 2
POST http://localhost:5000/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "polina",
  "password": "15101996Polina!",
  "role": "USER"
}

### Юзер 1 авторизовывается. Вытаскиваем токен.
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "kate",
  "password": "15101996Kate!"
}


### Юзер 1 создает 2 счета (повторить запрос)
POST http://localhost:5000/api/v1/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Проверяем, что счета создались
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Действие: Юзер 1 делает депозит на свой счет
POST http://localhost:5000/api/v1/accounts/deposit
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh
Content-Type: application/json

{
  "id": 1,
  "balance": 100
}

### Проверяем, что депозит 100 появился на счете "1"
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh


### Юзер 2 авторизуется. Вытаскиваем токен
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "polina",
  "password": "15101996Polina!"
}

### Юзер 2 создает счета (повторяем запрос 2 раза)
POST http://localhost:5000/api/v1/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==


### Проверяем, что счета создались и записываем их ID чтобы потом подставить
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==


### Действие: юзер 1 делает перевод на сумму 0 на несуществующий счет
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

{
  "senderAccountId": 3,
  "receiverAccountId": 100500,
  "amount": 50
}

### Результат: 400 bad request Invalid transfer: insufficient funds or invalid accounts

### Проверка: у юзера 1 баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Authorization: Basic a2F0ZToxNTEwMTk5NkthdGUh

### Проверка 2: у юзера 2 баланс такой же баланс такой же и инфо о транзакциях нет
GET http://localhost:5000/api/v1/customer/accounts
Authorization: Basic cG9saW5hOjE1MTAxOTk2UG9saW5hIQ==

### Удаляем данные: Админ получает id всех юзеров
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/2
Authorization: Basic YWRtaW46YWRtaW4=

### Удаляем данные: по id удаляем юзера
DELETE http://localhost:5000/api/v1/admin/users/3
Authorization: Basic YWRtaW46YWRtaW4=

### Проверяем, что пользователей нет
GET http://localhost:5000/api/v1/admin/users
Authorization: Basic YWRtaW46YWRtaW4=
